---
linters:
  enable-all: true

linters-settings:
  gofumpt:
    extra-rules: true
  unused:
    check-exported: true

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - gochecknoglobals
        - unused
